apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::734811867068:role/eks-cluster-terraform20190705154248234100000005
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::734811867068:role/Admin
      username: role1
      groups:
        - system:masters

  mapUsers: |

  mapAccounts: |

